[project]
name = 'time-travel-paradox-prevention-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.chronological-consensus-engine]
path = 'contracts/chronological-consensus-engine.clar'
clarity_version = 3
epoch = 3.1

[contracts.temporal-arbitrage-preventer]
path = 'contracts/temporal-arbitrage-preventer.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
